# Generated by Django 5.0.4 on 2024-10-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_arrival',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
